version: '3.4'

services:
#  orders.api:
#    image: ordersapi
#    build:
#      context: .
#      dockerfile: Orders.API/Dockerfile
#    depends_on:
#      - catalog.api
#      # - document.data
#
  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: mssqldb
    build:
      context: .
      dockerfile: db/Dockerfile

  # document.data:
  #   image: mongo
