version: '3.4'

services:
  orders.api:
    image: ${DOCKER_REGISTRY}ordersapi
    build:
      context: .
      dockerfile: Orders.API/Dockerfile
    depends_on:
      - catalog.api
      - graph.data

  catalog.api:
    image: ${DOCKER_REGISTRY}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  graph.data:
    image: neo4j:3.5
